use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fs;

use anneal_core::{
    ActorContext, CancellationToken, ConfigEntry, ConfigFacts, CorpusId, Generation,
};
use beam_file::chunk::RawChunk;
use eetf::{Atom, Binary, FixInteger, List, Map, Term, Tuple};
use serde_json::json;
use tempfile::tempdir;

use super::*;

fn context<'a>(root: &'a Utf8PathBuf, config: &'a ConfigFacts) -> SourceContext<'a> {
    context_for_roots(std::slice::from_ref(root), config)
}

fn context_for_roots<'a>(roots: &'a [Utf8PathBuf], config: &'a ConfigFacts) -> SourceContext<'a> {
    SourceContext {
        corpus: CorpusId::from("test"),
        roots,
        config_facts: config,
        probe_code_target_history: false,
        read_code_drift_evidence: false,
        refresh_code_drift_evidence: false,
        probe_edge_assertions: false,
        time_ref: None,
        previous_generation: Some(Generation::new(0)),
        actor: ActorContext {
            actor: "test".to_string(),
            capabilities: BTreeSet::new(),
        },
        cancellation: CancellationToken::new(),
    }
}

fn write_fixture(root: &Utf8Path) {
    fs::create_dir_all(root.join("src")).expect("create src");
    fs::create_dir_all(root.join("tests")).expect("create tests");
    fs::write(root.join("Cargo.toml"), "[package]\nname = \"demo\"\n").expect("write cargo");
    fs::write(
        root.join("src/lib.rs"),
        "pub struct Widget;\npub trait Other {}\npub fn make() -> Widget { Widget }\n",
    )
    .expect("write lib");
    fs::write(
        root.join("src/private.rs"),
        "fn helper() {}\n// TODO: tighten private helper\n",
    )
    .expect("write private");
    fs::write(
        root.join("src/generated.rs"),
        "// @generated by fixture\n// DO NOT EDIT\npub fn generated() {}\n",
    )
    .expect("write generated");
    fs::write(
        root.join("tests/integration.rs"),
        "#[test]\nfn smoke() {}\n",
    )
    .expect("write integration test");
    let rustdoc = json!({
        "root": 0,
        "crate_version": "0.1.0",
        "includes_private": false,
        "target": {"triple": "x86_64-unknown-linux-gnu", "target_features": []},
        "format_version": rustdoc_types::FORMAT_VERSION,
        "external_crates": {},
        "paths": {
            "0": {"crate_id": 0, "path": ["demo"], "kind": "module"},
            "1": {"crate_id": 0, "path": ["demo", "Widget"], "kind": "struct"},
            "2": {"crate_id": 0, "path": ["demo", "Other"], "kind": "trait"},
            "3": {"crate_id": 0, "path": ["demo", "make"], "kind": "function"}
        },
        "index": {
            "0": {
                "id": 0,
                "crate_id": 0,
                "name": "demo",
                "span": {"filename": "src/lib.rs", "begin": [1, 1], "end": [3, 1]},
                "visibility": "public",
                "docs": "Crate docs.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"module": {"is_crate": true, "items": [1, 2, 3], "is_stripped": false}}
            },
            "1": {
                "id": 1,
                "crate_id": 0,
                "name": "Widget",
                "span": {"filename": "src/lib.rs", "begin": [1, 1], "end": [1, 18]},
                "visibility": "public",
                "docs": "Widget docs with [Other].",
                "links": {"Other": 2},
                "attrs": [],
                "deprecation": null,
                "inner": {"struct": {"kind": "unit", "generics": {"params": [], "where_predicates": []}, "impls": []}}
            },
            "2": {
                "id": 2,
                "crate_id": 0,
                "name": "Other",
                "span": {"filename": "src/lib.rs", "begin": [2, 1], "end": [2, 19]},
                "visibility": "public",
                "docs": "Other docs.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"trait": {
                    "is_auto": false,
                    "is_unsafe": false,
                    "is_dyn_compatible": true,
                    "items": [],
                    "generics": {"params": [], "where_predicates": []},
                    "bounds": [],
                    "implementations": []
                }}
            },
            "3": {
                "id": 3,
                "crate_id": 0,
                "name": "make",
                "span": {"filename": "src/lib.rs", "begin": [3, 1], "end": [3, 40]},
                "visibility": "public",
                "docs": "Make a widget.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"function": {
                    "sig": {
                        "inputs": [],
                        "output": {"resolved_path": {"path": "demo::Widget", "id": 1, "args": null}},
                        "is_c_variadic": false
                    },
                    "generics": {"params": [], "where_predicates": []},
                    "header": {
                        "is_const": false,
                        "is_unsafe": false,
                        "is_async": false,
                        "abi": "Rust"
                    },
                    "has_body": true
                }}
            }
        }
    });
    fs::write(
        root.join("target/doc/demo.json"),
        serde_json::to_string_pretty(&rustdoc).expect("fixture json"),
    )
    .expect("write rustdoc");
}

fn atom(value: &str) -> Term {
    Term::from(Atom::from(value))
}

fn binary(value: &str) -> Term {
    Term::from(Binary::from(value.as_bytes()))
}

fn int(value: i32) -> Term {
    Term::from(FixInteger::from(value))
}

fn list(values: Vec<Term>) -> Term {
    Term::from(List::from(values))
}

fn tuple(values: Vec<Term>) -> Term {
    Term::from(Tuple::from(values))
}

fn map(values: Vec<(Term, Term)>) -> Term {
    Term::from(Map::from(values.into_iter().collect::<HashMap<_, _>>()))
}

fn doc(text: &str) -> Term {
    map(vec![(binary("en"), binary(text))])
}

fn metadata(values: Vec<(&str, Term)>) -> Term {
    map(values
        .into_iter()
        .map(|(key, value)| (atom(key), value))
        .collect())
}

fn eep48_docs_term() -> Term {
    let module_metadata = metadata(vec![
        ("source_path", binary("lib/herald/agent.ex")),
        ("behaviours", list(vec![atom("Herald.AgentBehaviour")])),
    ]);
    let entry_metadata = metadata(vec![
        ("deprecated", binary("use start/1")),
        ("since", binary("1.0")),
    ]);
    let entry = tuple(vec![
        tuple(vec![atom("function"), atom("run"), int(2)]),
        int(12),
        list(vec![binary(
            "run(agent :: Herald.Agent.t, opts :: Keyword.t) :: {:ok, String.t}",
        )]),
        doc("Run the agent. See [Guide](guides/agent.md)."),
        entry_metadata,
    ]);
    tuple(vec![
        atom("docs_v1"),
        int(1),
        atom("elixir"),
        atom("markdown"),
        doc("Agent module docs."),
        module_metadata,
        list(vec![entry]),
    ])
}

fn write_eep48_fixture(root: &Utf8Path) {
    fs::create_dir_all(root.join("lib/herald")).expect("create lib");
    fs::create_dir_all(root.join("_build/dev/lib/herald/ebin")).expect("create ebin");
    fs::write(
        root.join("mix.exs"),
        "defmodule Herald.MixProject do\nend\n",
    )
    .expect("write mix");
    fs::write(
            root.join("lib/herald/agent.ex"),
            "defmodule Herald.Agent do\n  @behaviour Herald.AgentBehaviour\n  def run(agent, opts), do: {:ok, agent}\nend\n\ndefimpl Herald.Protocol, for: Herald.Agent do\nend\n",
        )
        .expect("write elixir source");
    let mut docs = Vec::new();
    eep48_docs_term().encode(&mut docs).expect("encode docs");
    RawBeamFile {
        chunks: vec![RawChunk {
            id: *b"Docs",
            data: docs,
        }],
    }
    .to_file(root.join("_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam"))
    .expect("write beam");
}

fn code_meta<'a>(batch: &'a FactBatch, handle: &str, key: &str) -> Vec<&'a str> {
    batch
        .meta
        .iter()
        .filter(|meta| meta.handle == handle && meta.key == key)
        .map(|meta| meta.value.as_str())
        .collect()
}

fn handle_class(batch: &FactBatch, handle: &str) -> Option<String> {
    batch
        .meta
        .iter()
        .find(|meta| meta.handle == handle && meta.key == meta_key::CLASS)
        .map(|meta| meta.value.clone())
}

#[test]
fn rustdoc_source_projects_code_facts_without_raw_ids() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::PACKAGE, "demo"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.handles.iter().any(|handle| handle.id == "src/lib.rs"));
    let widget = batch
        .handles
        .iter()
        .find(|handle| {
            handle.kind == "section" && handle.id.starts_with("src/lib.rs#demo::Widget@")
        })
        .expect("widget handle");
    assert!(
        !widget.id.ends_with("#1"),
        "raw rustdoc ids must not become emitted handle ids"
    );
    assert!(batch.meta.iter().any(|meta| {
        meta.handle == widget.id
            && meta.key == meta_key::QUALIFIED_NAME
            && meta.value == "demo::Widget"
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.from == widget.id && edge.kind == edge_kind::CITES && edge.to.contains("demo::Other")
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.kind == edge_kind::USES_TYPE
            && edge.from.contains("demo::make")
            && edge.to == widget.id
    }));
    assert!(
        batch
            .content
            .iter()
            .any(|content| { content.handle == widget.id && content.text.contains("Widget docs") })
    );
    assert!(batch.meta.iter().any(|meta| {
        meta.handle == "Cargo.toml"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_COMPLETE
    }));
}

#[test]
fn rustdoc_source_declares_visible_content_budget_truncation() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::CONTENT_BUDGET_BYTES, "1"),
        ConfigEntry::scalar(config_key::MEMBER_DOC_BUDGET_BYTES, "8"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.meta.iter().any(|meta| {
        meta.handle == "Cargo.toml"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_TRUNCATED
    }));
    assert!(batch.meta.iter().any(|meta| {
        meta.handle.contains("demo::make")
            && meta.key == meta_key::CONTENT_BUDGET_DISPOSITION
            && meta.value == relation_value::PER_ITEM_CAP
    }));
}

#[test]
fn rustdoc_source_classifies_source_tree_files_and_obligations() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    let widget = batch
        .handles
        .iter()
        .find(|handle| {
            handle.kind == "section" && handle.id.starts_with("src/lib.rs#demo::Widget@")
        })
        .expect("widget handle");

    assert_eq!(
        handle_class(&batch, "src/lib.rs").as_deref(),
        Some(relation_value::CLASS_PUBLIC_API)
    );
    assert_eq!(
        handle_class(&batch, &widget.id).as_deref(),
        Some(relation_value::CLASS_PUBLIC_API)
    );
    assert_eq!(
        handle_class(&batch, "src/private.rs").as_deref(),
        Some(relation_value::CLASS_PRIVATE)
    );
    assert_eq!(
        handle_class(&batch, "tests/integration.rs").as_deref(),
        Some(relation_value::CLASS_TEST)
    );
    assert_eq!(
        handle_class(&batch, "src/generated.rs").as_deref(),
        Some(relation_value::CLASS_GENERATED)
    );
    assert!(batch.handles.iter().any(|handle| {
        handle.kind == "file" && handle.id == "src/private.rs" && handle.summary == "src/private.rs"
    }));
    assert_eq!(
        code_meta(&batch, "src/private.rs", meta_key::OBLIGATION_COUNT),
        vec!["1"]
    );
    assert!(
        code_meta(&batch, "src/private.rs", meta_key::OBLIGATION)
            .iter()
            .any(|value| value.starts_with("TODO:2:"))
    );
    assert!(batch.concerns.iter().any(|concern| {
        concern.name == concern_name::CODE_TODO && concern.member == "src/private.rs"
    }));
}

#[test]
fn source_root_alone_activates_file_level_extraction() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config facts");
    assert!(CodeSource::is_configured(&config));

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    assert!(
        batch
            .handles
            .iter()
            .any(|handle| handle.kind == "file" && handle.id == "src/lib.rs"),
        "standalone mode emits file handles from the source tree"
    );
    assert!(
        !batch.handles.iter().any(|handle| handle.kind == "section"),
        "no artifact means no item handles"
    );
    assert_eq!(
        handle_class(&batch, "src/private.rs").as_deref(),
        Some(relation_value::CLASS_PRIVATE)
    );
    assert_eq!(
        handle_class(&batch, "tests/integration.rs").as_deref(),
        Some(relation_value::CLASS_TEST)
    );
    assert!(batch.concerns.iter().any(|concern| {
        concern.name == concern_name::CODE_TODO && concern.member == "src/private.rs"
    }));
}

#[test]
fn git_tracked_scan_excludes_ignored_and_untracked_files() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("lib")).expect("create lib");
    fs::create_dir_all(root.join("priv")).expect("create priv");
    fs::write(root.join(".gitignore"), "priv/\n").expect("write gitignore");
    fs::write(root.join("lib/tracked.ex"), "defmodule Tracked do\nend\n").expect("write tracked");
    fs::write(root.join("priv/blob.ex"), "defmodule Ignored do\nend\n").expect("write ignored");
    fs::write(
        root.join("lib/untracked.ex"),
        "defmodule Untracked do\nend\n",
    )
    .expect("write untracked");
    for args in [
        &["init"][..],
        &["config", "user.email", "t@t.test"],
        &["config", "user.name", "t"],
        &["add", "lib/tracked.ex", ".gitignore"],
        &["commit", "-m", "init"],
    ] {
        let output = Command::new("git")
            .arg("-C")
            .arg(&root)
            .args(args)
            .output()
            .expect("run git");
        assert!(output.status.success(), "git {args:?} failed");
    }

    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::SOURCE_EXTENSION, "ex"),
    ])
    .expect("config facts");
    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    let ids: Vec<&str> = batch.handles.iter().map(|h| h.id.as_str()).collect();
    assert!(ids.contains(&"lib/tracked.ex"), "tracked source is scanned");
    assert!(
        !ids.iter().any(|id| id.contains("priv/")),
        "gitignored priv/ is never walked"
    );
    assert!(
        !ids.contains(&"lib/untracked.ex"),
        "untracked file is excluded in git mode"
    );
}

#[test]
fn source_extension_config_widens_the_file_level_scan() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("scripts")).expect("create scripts");
    fs::write(root.join("scripts/tool.py"), "# TODO: port me\n").expect("write py");
    fs::write(root.join("scripts/build.rs"), "fn main() {}\n").expect("write rs");
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::SOURCE_EXTENSION, "py"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    assert!(
        batch
            .handles
            .iter()
            .any(|handle| handle.id == "scripts/tool.py"),
        "configured extension is scanned"
    );
    assert!(
        !batch
            .handles
            .iter()
            .any(|handle| handle.id == "scripts/build.rs"),
        "explicit extension config replaces the default set"
    );
}

#[test]
fn rustdoc_source_projects_git_version_tags_as_package_metadata() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    for args in [
        &["init"][..],
        &["config", "user.email", "anneal@example.test"],
        &["config", "user.name", "Anneal Test"],
        &["add", "."],
        &["commit", "-m", "fixture"],
        &["tag", "demo-0.1.0"],
    ] {
        let output = Command::new("git")
            .arg("-C")
            .arg(&root)
            .args(args)
            .output()
            .expect("run git fixture command");
        assert!(
            output.status.success(),
            "git {:?} failed: {}{}",
            args,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let config = ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(
        config_key::RUSTDOC_JSON,
        "target/doc/demo.json",
    )])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.handles.iter().any(|handle| {
        handle.id == "code-version:demo-0.1.0"
            && handle.kind == "version"
            && handle.namespace == SOURCE_NAME
    }));
    assert_eq!(
        code_meta(&batch, "Cargo.toml", meta_key::VERSION_TAG),
        vec!["demo-0.1.0"]
    );
    assert!(batch.edges.iter().any(|edge| {
        edge.from == "Cargo.toml"
            && edge.to == "code-version:demo-0.1.0"
            && edge.kind == edge_kind::CONTAINS
    }));
}

#[test]
fn rustdoc_source_projects_each_root_independently() {
    let dir = tempdir().expect("tempdir");
    let root_a = Utf8PathBuf::from_path_buf(dir.path().join("a")).expect("utf8 tempdir");
    let root_b = Utf8PathBuf::from_path_buf(dir.path().join("b")).expect("utf8 tempdir");
    for root in [&root_a, &root_b] {
        fs::create_dir_all(root.join("target/doc")).expect("create target doc");
        write_fixture(root);
    }
    let roots = vec![root_a, root_b];
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context_for_roots(&roots, &config))
        .expect("code extraction");

    assert_eq!(
        batch
            .handles
            .iter()
            .filter(|handle| handle.kind == "file" && handle.id == "src/private.rs")
            .count(),
        2
    );
    assert_eq!(
        batch
            .meta
            .iter()
            .filter(|meta| {
                meta.handle == "src/private.rs"
                    && meta.key == meta_key::CLASS
                    && meta.value == relation_value::CLASS_PRIVATE
            })
            .count(),
        2
    );
}

#[test]
fn eep48_source_projects_elixir_docs_and_metadata() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    write_eep48_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(
            config_key::EEP48_BEAM,
            "_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam",
        ),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::PACKAGE, "herald"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    let module = "lib/herald/agent.ex#Herald.Agent";
    let member = "lib/herald/agent.ex#Herald.Agent.run/2";

    assert!(batch.handles.iter().any(|handle| {
        handle.id == module && handle.kind == "section" && handle.namespace == "module"
    }));
    assert!(batch.handles.iter().any(|handle| {
        handle.id == member && handle.status.as_deref() == Some("deprecated") && handle.line == 12
    }));
    assert_eq!(
        code_meta(&batch, module, meta_key::QUALIFIED_NAME),
        vec!["Herald.Agent"]
    );
    assert_eq!(
        code_meta(&batch, member, meta_key::QUALIFIED_NAME),
        vec!["Herald.Agent.run/2"]
    );
    assert_eq!(
        code_meta(&batch, member, meta_key::DEPRECATED_NOTE),
        vec!["use start/1"]
    );
    assert_eq!(code_meta(&batch, member, meta_key::SINCE), vec!["1.0"]);
    assert!(batch.edges.iter().any(|edge| {
        edge.from == module
            && edge.kind == edge_kind::IMPLEMENTS
            && edge.to.contains("Herald.AgentBehaviour")
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.from == member && edge.kind == edge_kind::CITES && edge.to.contains("guides")
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.from == member && edge.kind == edge_kind::USES_TYPE && edge.to.contains("String.t")
    }));
    assert!(
        batch
            .content
            .iter()
            .any(|content| { content.handle == member && content.text.contains("Run the agent") })
    );
    assert!(batch.edges.iter().any(|edge| {
        edge.file == "lib/herald/agent.ex"
            && edge.kind == edge_kind::IMPLEMENTS
            && edge.to.contains("Herald.Protocol")
    }));
}

#[test]
fn eep48_source_declares_member_doc_budget_truncation() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    write_eep48_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(
            config_key::EEP48_BEAM,
            "_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam",
        ),
        ConfigEntry::scalar(config_key::CONTENT_BUDGET_BYTES, "1"),
        ConfigEntry::scalar(config_key::MEMBER_DOC_BUDGET_BYTES, "8"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.meta.iter().any(|meta| {
        meta.handle == "mix.exs"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_TRUNCATED
    }));
    assert!(batch.meta.iter().any(|meta| {
        meta.handle == "lib/herald/agent.ex#Herald.Agent.run/2"
            && meta.key == meta_key::CONTENT_BUDGET_DISPOSITION
            && meta.value == relation_value::PER_ITEM_CAP
    }));
}
