//! Contract tests shared across rustdoc, EEP-48, and bare-source extraction.
//!
//! Fixtures assert that the three input paths converge on the same public fact
//! vocabulary while preserving format-specific provenance and budget signals.

use std::collections::BTreeSet;
use std::collections::HashMap;
use std::fs;

use anneal_core::{
    ActorContext, CancellationToken, ConfigEntry, ConfigFacts, CorpusId, Generation,
};
use beam_file::chunk::RawChunk;
use eetf::{Atom, Binary, FixInteger, List, Map, Term, Tuple};
use serde_json::json;
use tempfile::tempdir;

use super::*;

fn context<'a>(root: &'a Utf8PathBuf, config: &'a ConfigFacts) -> SourceContext<'a> {
    context_for_roots(std::slice::from_ref(root), config)
}

fn context_for_roots<'a>(roots: &'a [Utf8PathBuf], config: &'a ConfigFacts) -> SourceContext<'a> {
    SourceContext {
        corpus: CorpusId::from("test"),
        roots,
        config_facts: config,
        probe_code_target_history: false,
        read_code_drift_evidence: false,
        refresh_code_drift_evidence: false,
        probe_edge_assertions: false,
        time_ref: None,
        previous_generation: Some(Generation::new(0)),
        actor: ActorContext {
            actor: "test".to_string(),
            capabilities: BTreeSet::new(),
        },
        cancellation: CancellationToken::new(),
    }
}

fn write_fixture(root: &Utf8Path) {
    fs::create_dir_all(root.join("src")).expect("create src");
    fs::create_dir_all(root.join("tests")).expect("create tests");
    fs::write(root.join("Cargo.toml"), "[package]\nname = \"demo\"\n").expect("write cargo");
    fs::write(
        root.join("src/lib.rs"),
        "pub struct Widget;\npub trait Other {}\npub fn make() -> Widget { Widget }\n",
    )
    .expect("write lib");
    fs::write(
        root.join("src/private.rs"),
        "fn helper() {}\n// TODO: tighten private helper\n",
    )
    .expect("write private");
    fs::write(
        root.join("src/generated.rs"),
        "// @generated by fixture\n// DO NOT EDIT\npub fn generated() {}\n",
    )
    .expect("write generated");
    fs::write(
        root.join("tests/integration.rs"),
        "#[test]\nfn smoke() {}\n",
    )
    .expect("write integration test");
    let rustdoc = json!({
        "root": 0,
        "crate_version": "0.1.0",
        "includes_private": false,
        "target": {"triple": "x86_64-unknown-linux-gnu", "target_features": []},
        "format_version": rustdoc_types::FORMAT_VERSION,
        "external_crates": {},
        "paths": {
            "0": {"crate_id": 0, "path": ["demo"], "kind": "module"},
            "1": {"crate_id": 0, "path": ["demo", "Widget"], "kind": "struct"},
            "2": {"crate_id": 0, "path": ["demo", "Other"], "kind": "trait"},
            "3": {"crate_id": 0, "path": ["demo", "make"], "kind": "function"}
        },
        "index": {
            "0": {
                "id": 0,
                "crate_id": 0,
                "name": "demo",
                "span": {"filename": "src/lib.rs", "begin": [1, 1], "end": [3, 1]},
                "visibility": "public",
                "docs": "Crate docs.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"module": {"is_crate": true, "items": [1, 2, 3], "is_stripped": false}}
            },
            "1": {
                "id": 1,
                "crate_id": 0,
                "name": "Widget",
                "span": {"filename": "src/lib.rs", "begin": [1, 1], "end": [1, 18]},
                "visibility": "public",
                "docs": "Widget docs with [Other].",
                "links": {"Other": 2},
                "attrs": [],
                "deprecation": null,
                "inner": {"struct": {"kind": "unit", "generics": {"params": [], "where_predicates": []}, "impls": []}}
            },
            "2": {
                "id": 2,
                "crate_id": 0,
                "name": "Other",
                "span": {"filename": "src/lib.rs", "begin": [2, 1], "end": [2, 19]},
                "visibility": "public",
                "docs": "Other docs.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"trait": {
                    "is_auto": false,
                    "is_unsafe": false,
                    "is_dyn_compatible": true,
                    "items": [],
                    "generics": {"params": [], "where_predicates": []},
                    "bounds": [],
                    "implementations": []
                }}
            },
            "3": {
                "id": 3,
                "crate_id": 0,
                "name": "make",
                "span": {"filename": "src/lib.rs", "begin": [3, 1], "end": [3, 40]},
                "visibility": "public",
                "docs": "Make a widget.",
                "links": {},
                "attrs": [],
                "deprecation": null,
                "inner": {"function": {
                    "sig": {
                        "inputs": [],
                        "output": {"resolved_path": {"path": "demo::Widget", "id": 1, "args": null}},
                        "is_c_variadic": false
                    },
                    "generics": {"params": [], "where_predicates": []},
                    "header": {
                        "is_const": false,
                        "is_unsafe": false,
                        "is_async": false,
                        "abi": "Rust"
                    },
                    "has_body": true
                }}
            }
        }
    });
    fs::write(
        root.join("target/doc/demo.json"),
        serde_json::to_string_pretty(&rustdoc).expect("fixture json"),
    )
    .expect("write rustdoc");
}

fn atom(value: &str) -> Term {
    Term::from(Atom::from(value))
}

fn binary(value: &str) -> Term {
    Term::from(Binary::from(value.as_bytes()))
}

fn int(value: i32) -> Term {
    Term::from(FixInteger::from(value))
}

fn list(values: Vec<Term>) -> Term {
    Term::from(List::from(values))
}

fn tuple(values: Vec<Term>) -> Term {
    Term::from(Tuple::from(values))
}

fn map(values: Vec<(Term, Term)>) -> Term {
    Term::from(Map::from(values.into_iter().collect::<HashMap<_, _>>()))
}

fn doc(text: &str) -> Term {
    map(vec![(binary("en"), binary(text))])
}

fn metadata(values: Vec<(&str, Term)>) -> Term {
    map(values
        .into_iter()
        .map(|(key, value)| (atom(key), value))
        .collect())
}

fn eep48_docs_term() -> Term {
    let module_metadata = metadata(vec![
        ("source_path", binary("lib/herald/agent.ex")),
        ("behaviours", list(vec![atom("Herald.AgentBehaviour")])),
    ]);
    let entry_metadata = metadata(vec![
        ("deprecated", binary("use start/1")),
        ("since", binary("1.0")),
    ]);
    let entry = tuple(vec![
        tuple(vec![atom("function"), atom("run"), int(2)]),
        int(12),
        list(vec![binary(
            "run(agent :: Herald.Agent.t, opts :: Keyword.t) :: {:ok, String.t}",
        )]),
        doc("Run the agent. See [Guide](guides/agent.md)."),
        entry_metadata,
    ]);
    tuple(vec![
        atom("docs_v1"),
        int(1),
        atom("elixir"),
        atom("markdown"),
        doc("Agent module docs."),
        module_metadata,
        list(vec![entry]),
    ])
}

fn write_eep48_fixture(root: &Utf8Path) {
    fs::create_dir_all(root.join("lib/herald")).expect("create lib");
    fs::create_dir_all(root.join("_build/dev/lib/herald/ebin")).expect("create ebin");
    fs::write(
        root.join("mix.exs"),
        "defmodule Herald.MixProject do\nend\n",
    )
    .expect("write mix");
    fs::write(
            root.join("lib/herald/agent.ex"),
            "defmodule Herald.Agent do\n  @behaviour Herald.AgentBehaviour\n  def run(agent, opts), do: {:ok, agent}\nend\n\ndefimpl Herald.Protocol, for: Herald.Agent do\nend\n",
        )
        .expect("write elixir source");
    let mut docs = Vec::new();
    eep48_docs_term().encode(&mut docs).expect("encode docs");
    RawBeamFile {
        chunks: vec![RawChunk {
            id: *b"Docs",
            data: docs,
        }],
    }
    .to_file(root.join("_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam"))
    .expect("write beam");
}

fn code_meta<'a>(batch: &'a FactBatch, handle: &str, key: &str) -> Vec<&'a str> {
    batch
        .meta
        .iter()
        .filter(|meta| meta.handle.as_str() == handle && meta.key == key)
        .map(|meta| meta.value.as_str())
        .collect()
}

fn handle_class(batch: &FactBatch, handle: &str) -> Option<String> {
    batch
        .meta
        .iter()
        .find(|meta| meta.handle.as_str() == handle && meta.key == meta_key::CLASS)
        .map(|meta| meta.value.clone())
}

#[test]
fn rustdoc_source_projects_code_facts_without_raw_ids() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::PACKAGE, "demo"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(
        batch
            .handles
            .iter()
            .any(|handle| handle.id.as_str() == "src/lib.rs")
    );
    let widget = batch
        .handles
        .iter()
        .find(|handle| {
            handle.kind == "section" && handle.id.as_str().starts_with("src/lib.rs#demo::Widget@")
        })
        .expect("widget handle");
    assert!(
        !widget.id.as_str().ends_with("#1"),
        "raw rustdoc ids must not become emitted handle ids"
    );
    assert!(batch.meta.iter().any(|meta| {
        meta.handle == widget.id
            && meta.key == meta_key::QUALIFIED_NAME
            && meta.value == "demo::Widget"
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.from == widget.id
            && edge.kind == edge_kind::CITES
            && edge.to.as_str().contains("demo::Other")
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.kind == edge_kind::USES_TYPE
            && edge.from.as_str().contains("demo::make")
            && edge.to == widget.id
    }));
    assert!(
        batch
            .content
            .iter()
            .any(|content| { content.handle == widget.id && content.text.contains("Widget docs") })
    );
    assert!(batch.meta.iter().any(|meta| {
        meta.handle.as_str() == "Cargo.toml"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_COMPLETE
    }));
}

#[test]
fn rustdoc_source_declares_visible_content_budget_truncation() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::CONTENT_BUDGET_BYTES, "1"),
        ConfigEntry::scalar(config_key::MEMBER_DOC_BUDGET_BYTES, "8"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.meta.iter().any(|meta| {
        meta.handle.as_str() == "Cargo.toml"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_TRUNCATED
    }));
    assert!(batch.meta.iter().any(|meta| {
        meta.handle.as_str().contains("demo::make")
            && meta.key == meta_key::CONTENT_BUDGET_DISPOSITION
            && meta.value == relation_value::PER_ITEM_CAP
    }));
}

#[test]
fn rustdoc_source_classifies_source_tree_files_and_obligations() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    let widget = batch
        .handles
        .iter()
        .find(|handle| {
            handle.kind == "section" && handle.id.as_str().starts_with("src/lib.rs#demo::Widget@")
        })
        .expect("widget handle");

    assert_eq!(
        handle_class(&batch, "src/lib.rs").as_deref(),
        Some(relation_value::CLASS_PUBLIC_API)
    );
    assert_eq!(
        handle_class(&batch, widget.id.as_str()).as_deref(),
        Some(relation_value::CLASS_PUBLIC_API)
    );
    assert_eq!(
        handle_class(&batch, "src/private.rs").as_deref(),
        Some(relation_value::CLASS_PRIVATE)
    );
    assert_eq!(
        handle_class(&batch, "tests/integration.rs").as_deref(),
        Some(relation_value::CLASS_TEST)
    );
    assert_eq!(
        handle_class(&batch, "src/generated.rs").as_deref(),
        Some(relation_value::CLASS_GENERATED)
    );
    assert!(batch.handles.iter().any(|handle| {
        handle.kind == "file"
            && handle.id.as_str() == "src/private.rs"
            && handle.summary == "src/private.rs"
    }));
    assert_eq!(
        code_meta(&batch, "src/private.rs", meta_key::OBLIGATION_COUNT),
        vec!["1"]
    );
    assert!(
        code_meta(&batch, "src/private.rs", meta_key::OBLIGATION)
            .iter()
            .any(|value| value.starts_with("TODO:2:"))
    );
    assert!(batch.concerns.iter().any(|concern| {
        concern.name == concern_name::CODE_TODO && concern.member.as_str() == "src/private.rs"
    }));
}

#[test]
fn source_root_alone_activates_file_level_extraction() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config facts");
    assert!(CodeSource::is_configured(&config));

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    assert!(
        batch
            .handles
            .iter()
            .any(|handle| handle.kind == "file" && handle.id.as_str() == "src/lib.rs"),
        "standalone mode emits file handles from the source tree"
    );
    assert!(
        !batch.handles.iter().any(|handle| handle.kind == "section"),
        "no artifact means no item handles"
    );
    assert_eq!(
        handle_class(&batch, "src/private.rs").as_deref(),
        Some(relation_value::CLASS_PRIVATE)
    );
    assert_eq!(
        handle_class(&batch, "tests/integration.rs").as_deref(),
        Some(relation_value::CLASS_TEST)
    );
    assert!(batch.concerns.iter().any(|concern| {
        concern.name == concern_name::CODE_TODO && concern.member.as_str() == "src/private.rs"
    }));
}

#[test]
fn git_tracked_scan_excludes_ignored_and_untracked_files() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("lib")).expect("create lib");
    fs::create_dir_all(root.join("priv")).expect("create priv");
    fs::write(root.join(".gitignore"), "priv/\n").expect("write gitignore");
    fs::write(root.join("lib/tracked.ex"), "defmodule Tracked do\nend\n").expect("write tracked");
    fs::write(root.join("priv/blob.ex"), "defmodule Ignored do\nend\n").expect("write ignored");
    fs::write(
        root.join("lib/untracked.ex"),
        "defmodule Untracked do\nend\n",
    )
    .expect("write untracked");
    for args in [
        &["init"][..],
        &["config", "user.email", "t@t.test"],
        &["config", "user.name", "t"],
        &["add", "lib/tracked.ex", ".gitignore"],
        &["commit", "-m", "init"],
    ] {
        let output = Command::new("git")
            .arg("-C")
            .arg(&root)
            .args(args)
            .output()
            .expect("run git");
        assert!(output.status.success(), "git {args:?} failed");
    }

    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::SOURCE_EXTENSION, "ex"),
    ])
    .expect("config facts");
    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    let ids: Vec<&str> = batch.handles.iter().map(|h| h.id.as_str()).collect();
    assert!(ids.contains(&"lib/tracked.ex"), "tracked source is scanned");
    assert!(
        !ids.iter().any(|id| id.contains("priv/")),
        "gitignored priv/ is never walked"
    );
    assert!(
        !ids.contains(&"lib/untracked.ex"),
        "untracked file is excluded in git mode"
    );
}

#[test]
fn source_extension_config_widens_the_file_level_scan() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("scripts")).expect("create scripts");
    fs::write(root.join("scripts/tool.py"), "# TODO: port me\n").expect("write py");
    fs::write(root.join("scripts/build.rs"), "fn main() {}\n").expect("write rs");
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::SOURCE_EXTENSION, "py"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    assert!(
        batch
            .handles
            .iter()
            .any(|handle| handle.id.as_str() == "scripts/tool.py"),
        "configured extension is scanned"
    );
    assert!(
        !batch
            .handles
            .iter()
            .any(|handle| handle.id.as_str() == "scripts/build.rs"),
        "explicit extension config replaces the default set"
    );
}

#[test]
fn rustdoc_source_projects_git_version_tags_as_package_metadata() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    fs::create_dir_all(root.join("target/doc")).expect("create target doc");
    write_fixture(&root);
    for args in [
        &["init"][..],
        &["config", "user.email", "anneal@example.test"],
        &["config", "user.name", "Anneal Test"],
        &["add", "."],
        &["commit", "-m", "fixture"],
        &["tag", "demo-0.1.0"],
    ] {
        let output = Command::new("git")
            .arg("-C")
            .arg(&root)
            .args(args)
            .output()
            .expect("run git fixture command");
        assert!(
            output.status.success(),
            "git {:?} failed: {}{}",
            args,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let config = ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(
        config_key::RUSTDOC_JSON,
        "target/doc/demo.json",
    )])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.handles.iter().any(|handle| {
        handle.id.as_str() == "code-version:demo-0.1.0"
            && handle.kind == "version"
            && handle.namespace == SOURCE_NAME
    }));
    assert_eq!(
        code_meta(&batch, "Cargo.toml", meta_key::VERSION_TAG),
        vec!["demo-0.1.0"]
    );
    assert!(batch.edges.iter().any(|edge| {
        edge.from.as_str() == "Cargo.toml"
            && edge.to.as_str() == "code-version:demo-0.1.0"
            && edge.kind == edge_kind::CONTAINS
    }));
    let tag_edge = batch
        .edges
        .iter()
        .find(|edge| edge.to.as_str() == "code-version:demo-0.1.0")
        .expect("old tag edge");
    let output = Command::new("git")
        .arg("-C")
        .arg(&root)
        .args(["tag", "aaa-unrelated"])
        .output()
        .expect("new tag");
    assert!(output.status.success());
    let expanded = CodeSource
        .extract(&context(&root, &config))
        .expect("new snapshot");
    assert!(
        expanded.edges.contains(tag_edge),
        "an earlier unrelated tag must not rename an existing version edge"
    );
}

#[test]
fn rustdoc_source_projects_each_root_independently() {
    let dir = tempdir().expect("tempdir");
    let root_a = Utf8PathBuf::from_path_buf(dir.path().join("a")).expect("utf8 tempdir");
    let root_b = Utf8PathBuf::from_path_buf(dir.path().join("b")).expect("utf8 tempdir");
    for root in [&root_a, &root_b] {
        fs::create_dir_all(root.join("target/doc")).expect("create target doc");
        write_fixture(root);
    }
    let roots = vec![root_a, root_b];
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context_for_roots(&roots, &config))
        .expect("code extraction");

    assert_eq!(
        batch
            .handles
            .iter()
            .filter(|handle| handle.kind == "file" && handle.id.as_str() == "src/private.rs")
            .count(),
        2
    );
    assert_eq!(
        batch
            .meta
            .iter()
            .filter(|meta| {
                meta.handle.as_str() == "src/private.rs"
                    && meta.key == meta_key::CLASS
                    && meta.value == relation_value::CLASS_PRIVATE
            })
            .count(),
        2
    );
}

#[test]
fn eep48_source_projects_elixir_docs_and_metadata() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    write_eep48_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(
            config_key::EEP48_BEAM,
            "_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam",
        ),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
        ConfigEntry::scalar(config_key::PACKAGE, "herald"),
        ConfigEntry::scalar(config_key::ARTIFACT_REVISION, "abc123"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");
    let module = "lib/herald/agent.ex#Herald.Agent";
    let member = "lib/herald/agent.ex#Herald.Agent.run/2";

    assert!(batch.handles.iter().any(|handle| {
        handle.id.as_str() == module && handle.kind == "section" && handle.namespace == "module"
    }));
    assert!(batch.handles.iter().any(|handle| {
        handle.id.as_str() == member
            && handle.status.as_deref() == Some("deprecated")
            && handle.line == 12
    }));
    assert_eq!(
        code_meta(&batch, module, meta_key::QUALIFIED_NAME),
        vec!["Herald.Agent"]
    );
    assert_eq!(
        code_meta(&batch, member, meta_key::QUALIFIED_NAME),
        vec!["Herald.Agent.run/2"]
    );
    assert_eq!(
        code_meta(&batch, member, meta_key::DEPRECATED_NOTE),
        vec!["use start/1"]
    );
    assert_eq!(code_meta(&batch, member, meta_key::SINCE), vec!["1.0"]);
    assert!(batch.edges.iter().any(|edge| {
        edge.from.as_str() == module
            && edge.kind == edge_kind::IMPLEMENTS
            && edge.to.as_str().contains("Herald.AgentBehaviour")
    }));
    assert!(
        !batch
            .edges
            .iter()
            .any(|edge| edge.from.as_str() == member && edge.kind == edge_kind::CITES)
    );
    assert!(
        !batch
            .handles
            .iter()
            .any(|handle| handle.id.as_str().contains("guides"))
    );
    assert!(batch.edges.iter().any(|edge| {
        edge.from.as_str() == member
            && edge.kind == edge_kind::USES_TYPE
            && edge.to.as_str().contains("String.t")
    }));
    assert!(batch.content.iter().any(|content| {
        content.handle.as_str() == member && content.text.contains("Run the agent")
    }));
    assert!(batch.edges.iter().any(|edge| {
        edge.file == "lib/herald/agent.ex"
            && edge.kind == edge_kind::IMPLEMENTS
            && edge.to.as_str().contains("Herald.Protocol")
    }));
}

#[test]
fn eep48_member_namespaces_merge_and_resolve_documented_links() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    write_eep48_fixture(&root);
    let entries = ["function", "callback", "type", "macrocallback", "macro"]
        .into_iter()
        .map(|kind| {
            tuple(vec![
                tuple(vec![
                    atom(kind),
                    atom(if matches!(kind, "macro" | "macrocallback") {
                        "other"
                    } else {
                        "run"
                    }),
                    int(2),
                ]),
                int(12),
                list(vec![binary("run(x, y)")]),
                doc("Member docs."),
                metadata(vec![]),
            ])
        })
        .collect();
    let term = tuple(vec![
        atom("docs_v1"),
        int(1),
        atom("elixir"),
        atom("markdown"),
        doc(
            "[callback](c:run/2) [type](t:Herald.Agent.run/2) [remote](c:Herald.Other.run/2) [missing](t:unknown/0) [function](`Herald.Agent.run/2`) [module](`m:Herald.Agent`)",
        ),
        metadata(vec![("source_path", binary("lib/herald/agent.ex"))]),
        list(entries),
    ]);
    let mut bytes = Vec::new();
    term.encode(&mut bytes).expect("encode docs");
    fs::write(root.join("Elixir.Herald.Agent.chunk"), bytes).expect("write docs");
    fs::write(
        root.join("lib/herald/other.ex"),
        "defmodule Herald.Other do\nend\n",
    )
    .expect("other source");
    let other = tuple(vec![
        atom("docs_v1"),
        int(1),
        atom("elixir"),
        atom("markdown"),
        doc("Other docs."),
        metadata(vec![("source_path", binary("lib/herald/other.ex"))]),
        list(vec![tuple(vec![
            tuple(vec![atom("callback"), atom("run"), int(2)]),
            int(1),
            list(vec![]),
            doc("Other callback."),
            metadata(vec![]),
        ])]),
    ]);
    let mut bytes = Vec::new();
    other.encode(&mut bytes).expect("encode other docs");
    fs::write(root.join("Elixir.Herald.Other.chunk"), bytes).expect("write other docs");
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::EEP48_DOC_CHUNK, "Elixir.Herald.Other.chunk"),
        ConfigEntry::scalar(config_key::EEP48_DOC_CHUNK, "Elixir.Herald.Agent.chunk"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
    ])
    .expect("config");
    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("extract");
    anneal_core::FactStore::default()
        .merge(batch.clone())
        .expect("distinct member namespaces merge");
    let base = "lib/herald/agent.ex#";
    let expected = [
        "Herald.Agent.run/2",
        "c:Herald.Agent.run/2",
        "t:Herald.Agent.run/2",
        "c:Herald.Agent.other/2",
        "Herald.Agent.other/2",
    ];
    for member in expected {
        let handle = format!("{base}{member}");
        assert!(batch.handles.iter().any(|row| row.id.as_str() == handle));
        assert!(batch.spans.iter().any(|row| row.handle.as_str() == handle
            && row.identity.native_id.as_str() == format!("{handle}#docs")));
        assert!(
            batch
                .content
                .iter()
                .any(|row| row.handle.as_str() == handle)
        );
    }
    for member in &expected[..3] {
        assert!(batch.edges.iter().any(
            |row| row.kind == edge_kind::CITES && row.to.as_str() == format!("{base}{member}")
        ));
    }
    assert!(
        batch.edges.iter().any(|row| row.kind == edge_kind::CITES
            && row.to.as_str() == "lib/herald/agent.ex#Herald.Agent")
    );
    assert!(batch.edges.iter().any(|row| row.kind == edge_kind::CITES
        && row.to.as_str() == "lib/herald/other.ex#c:Herald.Other.run/2"));
    assert!(batch.edges.iter().any(|row| row.kind == edge_kind::CITES
        && row.to.as_str().starts_with("elixir://")
        && row.to.as_str().contains("unknown")));
}

#[test]
fn eep48_source_declares_member_doc_budget_truncation() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 tempdir");
    write_eep48_fixture(&root);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(
            config_key::EEP48_BEAM,
            "_build/dev/lib/herald/ebin/Elixir.Herald.Agent.beam",
        ),
        ConfigEntry::scalar(config_key::CONTENT_BUDGET_BYTES, "1"),
        ConfigEntry::scalar(config_key::MEMBER_DOC_BUDGET_BYTES, "8"),
    ])
    .expect("config facts");

    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("code extraction");

    assert!(batch.meta.iter().any(|meta| {
        meta.handle.as_str() == "mix.exs"
            && meta.key == meta_key::CONTENT_BUDGET_ROOT_DISPOSITION
            && meta.value == relation_value::BUDGET_TRUNCATED
    }));
    assert!(batch.meta.iter().any(|meta| {
        meta.handle.as_str() == "lib/herald/agent.ex#Herald.Agent.run/2"
            && meta.key == meta_key::CONTENT_BUDGET_DISPOSITION
            && meta.value == relation_value::PER_ITEM_CAP
    }));
}

#[test]
fn rustdoc_same_location_member_bindings_follow_semantic_tie_order() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 root");
    fs::create_dir_all(root.join("target/doc")).expect("artifact directory");
    write_fixture(&root);
    let path = root.join("target/doc/demo.json");
    let mut artifact: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&path).expect("fixture")).expect("json");
    artifact["paths"]
        .as_object_mut()
        .expect("paths")
        .remove("3");
    let mut twin = artifact["index"]["3"].clone();
    twin["id"] = json!(4);
    twin["inner"]["function"]["sig"]["inputs"] = json!([["different", {"primitive":"u64"}]]);
    artifact["index"]["4"] = twin;
    artifact["index"]["0"]["inner"]["module"]["items"] = json!([1, 2, 3, 4]);
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
    ])
    .expect("config");
    let mut baseline = None;
    for iteration in 0..24 {
        if iteration % 2 == 1 {
            let mut left = artifact["index"]["3"].clone();
            let mut right = artifact["index"]["4"].clone();
            left["id"] = json!(4);
            right["id"] = json!(3);
            artifact["index"]["3"] = right;
            artifact["index"]["4"] = left;
        }
        fs::write(&path, serde_json::to_vec(&artifact).expect("encode")).expect("write");
        let batch = CodeSource
            .extract(&context(&root, &config))
            .expect("extract");
        let mut rows = batch
            .content
            .iter()
            .map(|row| serde_json::to_string(row).expect("row"))
            .collect::<Vec<_>>();
        rows.sort();
        if let Some(expected) = &baseline {
            assert_eq!(
                &rows, expected,
                "raw item ids and HashMap encounter order must not bind method payloads"
            );
        } else {
            baseline = Some(rows);
        }
    }
}

#[test]
fn code_fact_identity_uses_own_fields_and_local_multiplicity() {
    let mut before = CodeFactIds::default();
    let mut after = CodeFactIds::default();
    let first = before.edge(
        ("a", "Implements", "b"),
        ("impl.rs", 4),
        ("trait_impl", "impl B for A"),
    );
    let duplicate = before.edge(
        ("a", "Implements", "b"),
        ("impl.rs", 4),
        ("trait_impl", "impl B for A"),
    );
    after.edge(("unrelated", "Contains", "new"), ("first.rs", 1), ("", ""));
    assert_eq!(
        first,
        after.edge(
            ("a", "Implements", "b"),
            ("impl.rs", 4),
            ("trait_impl", "impl B for A")
        )
    );
    assert_eq!(
        duplicate,
        after.edge(
            ("a", "Implements", "b"),
            ("impl.rs", 4),
            ("trait_impl", "impl B for A")
        )
    );
    assert_ne!(first, duplicate);
    assert_ne!(
        first,
        after.edge(
            ("a", "Implements", "b"),
            ("other.rs", 4),
            ("trait_impl", "impl B for A")
        )
    );
    assert_ne!(
        first,
        after.edge(
            ("a", "Implements", "b"),
            ("impl.rs", 4),
            ("trait_impl", "impl B for A where T: Bound")
        )
    );
    let mut ids = CodeFactIds::default();
    assert_ne!(
        ids.edge(("a::b", "Cites", "c"), ("x", 1), ("", "")),
        ids.edge(("a", "b::Cites", "c"), ("x", 1), ("", ""))
    );
}

#[test]
fn code_source_unrelated_impl_and_fixme_preserve_existing_id_bindings() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("root");
    fs::create_dir_all(&root).expect("mkdir");
    fs::write(root.join("mix.exs"), "defmodule Demo.MixProject do\nend\n").expect("mix");
    fs::write(
        root.join("b.ex"),
        "\n# TODO: old\n# TODO: second\ndefimpl Existing, for: Target do\nend\n",
    )
    .expect("source");
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config");
    let old = CodeSource
        .extract(&context(&root, &config))
        .expect("before");
    fs::write(root.join("a.ex"), "defimpl First, for: Other do\nend\n").expect("new file");
    fs::write(
        root.join("b.ex"),
        "# FIXME: new\n# TODO: old\n# TODO: second\ndefimpl Existing, for: Target do\nend\n",
    )
    .expect("same old lines");
    let new = CodeSource.extract(&context(&root, &config)).expect("after");
    for edge in &old.edges {
        assert!(
            new.edges.contains(edge),
            "existing implementation id and payload stay identical"
        );
    }
    for meta in old.meta.iter().filter(|row| {
        row.key == meta_key::OBLIGATION
            || row.key == meta_key::IMPLEMENTS_KIND
            || row.key == meta_key::IMPLEMENTS_SIGNATURE
    }) {
        assert!(
            new.meta.contains(meta),
            "existing evidence id and owner stay identical"
        );
    }
    for concern in &old.concerns {
        assert!(
            new.concerns.contains(concern),
            "TODO identities do not move when FIXME arrives"
        );
    }
    assert_eq!(new.edges.len(), old.edges.len() + 1);
    assert_eq!(new.concerns.len(), old.concerns.len() + 1);
    let mut legacy = old;
    let mut old_to_legacy = BTreeMap::new();
    for (index, edge) in legacy.edges.iter_mut().enumerate() {
        let replacement = format!("legacy-{index}");
        old_to_legacy.insert(
            edge.identity.native_id.as_str().to_string(),
            replacement.clone(),
        );
        edge.identity.native_id = NativeId::from(replacement);
    }
    for meta in &mut legacy.meta {
        if let Some(replacement) = old_to_legacy.get(meta.identity.native_id.as_str()) {
            meta.identity.native_id = NativeId::from(replacement.clone());
            meta.handle = handle_id(replacement);
        }
    }
    let mut store = anneal_core::FactStore::default();
    store.merge(legacy).expect("legacy snapshot");
    store.merge(new).expect("fresh full snapshot");
    assert!(
        store
            .edges()
            .iter()
            .all(|row| !row.identity.native_id.as_str().starts_with("legacy-"))
    );
    assert!(store.meta().iter().all(
        |row| !row.identity.native_id.as_str().starts_with("legacy-")
            && !row.handle.as_str().starts_with("legacy-")
    ));
}

#[test]
fn rustdoc_same_line_impl_evidence_permutations_keep_full_bytes() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("root");
    fs::create_dir_all(root.join("target/doc")).expect("artifact dir");
    write_fixture(&root);
    let path = root.join("target/doc/demo.json");
    let mut artifact: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&path).expect("fixture")).expect("json");
    for (id, blanket) in [(4, "A"), (5, "B")] {
        artifact["index"][id.to_string()] = json!({"id":id,"crate_id":0,"name":null,
            "span":{"filename":"src/lib.rs","begin":[4,1],"end":[4,20]},
            "visibility":"public","docs":null,"links":{},"attrs":[],"deprecation":null,
            "inner":{"impl":{"is_unsafe":false,"generics":{"params":[],"where_predicates":[]},
                "provided_trait_methods":[],"trait":{"path":"demo::Other","id":2,"args":null},
                "for":{"resolved_path":{"path":"demo::Widget","id":1,"args":null}},
                "items":[],"is_negative":false,"is_synthetic":false,"blanket_impl":{"generic":blanket}}}});
    }
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::RUSTDOC_JSON, "target/doc/demo.json"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
    ])
    .expect("config");
    let mut baseline = None;
    for iteration in 0..16 {
        if iteration % 2 == 1 {
            let mut left = artifact["index"]["4"].clone();
            let mut right = artifact["index"]["5"].clone();
            left["id"] = json!(5);
            right["id"] = json!(4);
            artifact["index"]["4"] = right;
            artifact["index"]["5"] = left;
        }
        fs::write(&path, serde_json::to_vec(&artifact).expect("encode")).expect("write");
        let batch = CodeSource
            .extract(&context(&root, &config))
            .expect("extract");
        let mut edges = batch
            .edges
            .iter()
            .map(|row| serde_json::to_string(row).expect("row"))
            .collect::<Vec<_>>();
        edges.sort();
        let mut meta = batch
            .meta
            .iter()
            .map(|row| serde_json::to_string(row).expect("row"))
            .collect::<Vec<_>>();
        meta.sort();
        let rows = (edges, meta);
        if let Some(expected) = &baseline {
            assert_eq!(
                &rows, expected,
                "owned signatures bind to the same edge ids under permutation"
            );
        } else {
            baseline = Some(rows);
        }
    }
}

#[test]
fn eep48_behaviours_resolve_modules_before_emission() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 root");
    fs::create_dir_all(root.join("lib")).expect("source directory");
    for (module, file, behaviours) in [
        (
            "Herald.Agent",
            "agent.ex",
            vec![
                atom("Elixir.Herald.Internal"),
                atom("Elixir.Dependency.Missing"),
            ],
        ),
        ("Herald.Internal", "internal.ex", vec![]),
    ] {
        fs::write(
            root.join(format!("lib/{file}")),
            format!("defmodule {module} do\nend\n"),
        )
        .expect("source");
        let term = tuple(vec![
            atom("docs_v1"),
            int(1),
            atom("elixir"),
            atom("markdown"),
            doc("Docs."),
            metadata(vec![
                ("source_path", binary(&format!("lib/{file}"))),
                ("behaviours", list(behaviours)),
            ]),
            list(vec![]),
        ]);
        let mut bytes = Vec::new();
        term.encode(&mut bytes).expect("encode");
        fs::write(root.join(format!("Elixir.{module}.chunk")), bytes).expect("artifact");
    }
    let config = ConfigFacts::try_from_entries(vec![
        ConfigEntry::scalar(config_key::EEP48_DOC_CHUNK, "Elixir.Herald.Agent.chunk"),
        ConfigEntry::scalar(config_key::EEP48_DOC_CHUNK, "Elixir.Herald.Internal.chunk"),
        ConfigEntry::scalar(config_key::SOURCE_ROOT, "."),
    ])
    .expect("config");
    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("extract");
    let internal = batch
        .edges
        .iter()
        .find(|e| {
            e.kind == edge_kind::IMPLEMENTS && e.to.as_str() == "lib/internal.ex#Herald.Internal"
        })
        .expect("internal module target");
    assert_eq!(
        code_meta(
            &batch,
            internal.identity.native_id.as_str(),
            meta_key::IMPLEMENTS_SIGNATURE
        ),
        vec!["@behaviour Elixir.Herald.Internal"]
    );
    assert!(batch.edges.iter().any(|e| e.kind == edge_kind::IMPLEMENTS
        && e.to.as_str() == "elixir://Elixir.Dependency.Missing"));
    assert!(
        !batch
            .handles
            .iter()
            .any(|h| h.id.as_str() == "elixir://Elixir.Herald.Internal")
    );
    assert!(
        !batch
            .meta
            .iter()
            .any(|m| m.handle.as_str() == "elixir://Elixir.Herald.Internal")
    );
    anneal_core::FactStore::default()
        .merge(batch)
        .expect("merge");
}

#[test]
fn source_protocol_names_exclude_implicit_for_do_token() {
    let dir = tempdir().expect("tempdir");
    let root = Utf8PathBuf::from_path_buf(dir.path().join("corpus")).expect("utf8 root");
    fs::create_dir_all(root.join("lib")).expect("source directory");
    fs::write(root.join("lib/item.ex"), "defmodule Demo.Item do\n  defimpl String.Chars do\n  end\n  defimpl Inspect   do # comment\n  end\nend\ndefimpl Jason.Encoder, for: Demo.Item do\nend\n").expect("source");
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config");
    let batch = CodeSource
        .extract(&context(&root, &config))
        .expect("extract");
    let targets = batch
        .edges
        .iter()
        .filter(|e| e.kind == edge_kind::IMPLEMENTS)
        .map(|e| e.to.as_str())
        .collect::<BTreeSet<_>>();
    assert_eq!(
        targets,
        BTreeSet::from([
            "elixir://String.Chars",
            "elixir://Inspect",
            "elixir://Jason.Encoder"
        ])
    );
    assert!(
        !batch
            .meta
            .iter()
            .any(|m| m.key == meta_key::IMPLEMENTS_SIGNATURE && m.value.contains("do"))
    );
}

#[test]
fn explicit_markdown_links_only_keep_code_destinations() {
    let text = r"[http](https://example.com) [anchor](#section) [mail](mailto:x@y) [ftp](ftp://example.com) [file](guide.md) [extras](`e:elixir:writing.md`) [module](`m:Herald.Agent`) [function](`Herald.Agent.run/2`) [callback](`c:Herald.Agent.run/2`) [type](t:run/2) [erlang](`:ets.new/2`)
`[literal](Wrong.Module)`

~~~
[example](Another.Module)
~~~
";
    assert_eq!(
        eep48::markdown_links(text),
        vec![
            ":ets.new/2",
            "Herald.Agent.run/2",
            "c:Herald.Agent.run/2",
            "m:Herald.Agent",
            "t:run/2"
        ]
    );
}

struct RepositoryFixture {
    _temp: tempfile::TempDir,
    anchor: Utf8PathBuf,
    desk: Utf8PathBuf,
}

fn repository_command(root: &Utf8Path, program: &str, args: &[&str]) -> String {
    let output = Command::new(program)
        .current_dir(root)
        .env_remove("GIT_DIR")
        .env_remove("GIT_WORK_TREE")
        .env_remove("GIT_COMMON_DIR")
        .env("GIT_AUTHOR_NAME", "Test")
        .env("GIT_AUTHOR_EMAIL", "test@example.test")
        .env("GIT_COMMITTER_NAME", "Test")
        .env("GIT_COMMITTER_EMAIL", "test@example.test")
        .args(args)
        .output()
        .expect("repository fixture command");
    assert!(
        output.status.success(),
        "{program} {args:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("UTF-8 fixture output")
        .trim()
        .to_owned()
}

fn repository_fixture() -> Option<RepositoryFixture> {
    if !Command::new("jj")
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
    {
        assert!(
            std::env::var_os("ANNEAL_REQUIRE_JJ").is_none(),
            "jj source fixture requires jj (ANNEAL_REQUIRE_JJ)"
        );
        eprintln!("jj source fixture skipped: jj executable unavailable");
        return None;
    }
    let temp = tempdir().expect("tempdir");
    let outer = Utf8PathBuf::from_path_buf(temp.path().join("outer")).expect("UTF-8");
    let anchor = outer.join("anchor");
    let desk = outer.join("desk");
    fs::create_dir_all(&anchor).expect("anchor");
    repository_command(&outer, "git", &["init", "--quiet"]);
    repository_command(&anchor, "git", &["init", "--quiet"]);
    for path in ["alpha.rs", "beta.rs"] {
        fs::write(anchor.join(path), "pub fn fixture() {}\n").expect("source");
    }
    repository_command(&anchor, "git", &["add", "."]);
    repository_command(&anchor, "git", &["commit", "--quiet", "-m", "project"]);
    repository_command(&anchor, "git", &["tag", "parent-tag"]);
    repository_command(&anchor, "jj", &["git", "init", "--colocate"]);
    repository_command(&anchor, "jj", &["workspace", "add", desk.as_str()]);
    fs::write(desk.join("home-only.rs"), "pub fn unrelated() {}\n").expect("unrelated file");
    repository_command(
        &outer,
        "git",
        &["add", "desk/alpha.rs", "desk/home-only.rs"],
    );
    repository_command(&outer, "git", &["commit", "--quiet", "-m", "ancestor"]);
    repository_command(&outer, "git", &["tag", "outer-tag"]);
    Some(RepositoryFixture {
        _temp: temp,
        anchor,
        desk,
    })
}

#[test]
fn jj_source_uses_pinned_tree_and_tags_instead_of_ancestor_git() {
    let Some(fixture) = repository_fixture() else {
        return;
    };
    let before = repository_command(
        &fixture.desk,
        "jj",
        &["--ignore-working-copy", "debug", "working-copy"],
    );
    let repository = anneal_core::RepositoryContext::discover(&fixture.desk);
    let pin = repository.jj_pin().expect("pin");
    repository_command(&fixture.anchor, "git", &["tag", "pin-tag", pin]);
    let repository = anneal_core::RepositoryContext::discover(&fixture.desk);
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config");
    let batch = CodeSource::extract_with_repository(&context(&fixture.desk, &config), &repository)
        .expect("code extraction");
    let files = batch
        .handles
        .iter()
        .filter(|h| h.kind == "file")
        .map(|h| h.id.as_str())
        .collect::<BTreeSet<_>>();
    assert_eq!(files, BTreeSet::from(["alpha.rs", "beta.rs"]));
    let versions = batch
        .handles
        .iter()
        .filter(|h| h.kind == "version")
        .map(|h| h.id.as_str())
        .collect::<Vec<_>>();
    assert_eq!(versions, ["code-version:pin-tag"]);
    assert!(repository.finish_jj_generation());
    assert_eq!(
        before,
        repository_command(
            &fixture.desk,
            "jj",
            &["--ignore-working-copy", "debug", "working-copy"]
        )
    );
}

#[test]
fn jj_tag_failure_leaves_tracked_file_discovery_available() {
    let Some(fixture) = repository_fixture() else {
        return;
    };
    let repository = anneal_core::RepositoryContext::discover(&fixture.desk);
    repository.fail_jj_operation(
        anneal_core::RepositoryOperation::VersionTags,
        "fixture-tag-probe-failed",
    );
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config");
    let batch = CodeSource::extract_with_repository(&context(&fixture.desk, &config), &repository)
        .expect("files remain available");
    assert_eq!(batch.handles.iter().filter(|h| h.kind == "file").count(), 2);
    assert!(!batch.handles.iter().any(|h| h.kind == "version"));
    assert!(!repository.operation_available(anneal_core::RepositoryOperation::VersionTags));
    assert_eq!(
        repository.operation_reason(anneal_core::RepositoryOperation::VersionTags),
        "fixture-tag-probe-failed"
    );
    assert!(repository.operation_available(anneal_core::RepositoryOperation::ChangeHistory));
    assert!(repository.operation_available(anneal_core::RepositoryOperation::TargetHistory));
    assert!(repository.operation_available(anneal_core::RepositoryOperation::IgnoreIndex));
    assert!(repository.finish_jj_generation());
    repository.fail_jj_operation(
        anneal_core::RepositoryOperation::IgnoreIndex,
        "fixture-tracked-probe-failed",
    );
    assert!(
        CodeSource::extract_with_repository(&context(&fixture.desk, &config), &repository)
            .expect_err("unavailable VCS must not walk files")
            .to_string()
            .contains("fixture-tracked-probe-failed")
    );
}

#[test]
fn jj_code_batch_cannot_be_merged_after_its_pin_moves() {
    let Some(fixture) = repository_fixture() else {
        return;
    };
    let repository = anneal_core::RepositoryContext::discover(&fixture.desk);
    let config =
        ConfigFacts::try_from_entries(vec![ConfigEntry::scalar(config_key::SOURCE_ROOT, ".")])
            .expect("config");
    let batch = CodeSource::extract_with_repository(&context(&fixture.desk, &config), &repository)
        .expect("initial batch");
    assert!(!batch.handles.is_empty());
    repository_command(&fixture.desk, "jj", &["new"]);
    assert!(
        !repository.finish_jj_generation(),
        "driver must reject old-pin facts"
    );
    assert!(!repository.operation_available(anneal_core::RepositoryOperation::VersionTags));
    assert!(
        CodeSource::extract_with_repository(&context(&fixture.desk, &config), &repository).is_err()
    );
}
